name: Terraform Infrastructure

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TF_VERSION: 1.5.0
  PROJECT_ID: paradox-intern
  PROJECT_NUMBER: "855262384811"
  REGION: asia-northeast3

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false -out=tfplan \
            -var="github_owner=${{ github.repository_owner }}" \
            -var="database_url=${{ secrets.DATABASE_URL }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -input=false tfplan
